### ISSUE TITLE
change <require> maven version to 3.8.8 as it's the oldest maintained version

### ISSUE THREAD

**Issue by bdhave** [jonathanlermitage/oga-maven-plugin#87]
see https://endoflife.date/maven

**Comment by jonathanlermitage** [comment]
I did not test with older maven versions (like 3.3) since a while, but if it still works, I don't see any reason to enforce the minimum maven version.  

I already worked for companies that stay on unmaintained maven (and other tools) versions. I know this is a bad practice, but this is their problem and, sometimes, there are (good/bad) reasons behind that. Per example, I worked on critical stuff for a big company, we worked offline, and every tool we were using was approved by a security team. And approval can take ages... It was a nightmare for developers, but I think I understand why they do that (validating things, not taking one year just for validating a new tool version 😅).

**Comment by jonathanlermitage** [comment]
9 years old or 20 years old, I think it doesn't matter. I don't want to break something if there is no benefit to it.

**Comment by hazendaz** [comment]
Just an fwi, but maven team sent out notices a while ago to user community to move baselines to 3.6.3.  I think that should be reconsidered as it ensures maven 4 compatibility long term.  Most major plugins outside maven space also now require the same, so it's sort of unlikely to use older.

It's trivial to setup github actions to run lowest, latest, and maven 4.  I've done so on spotbugs maven plugin and others.  I'd be happy to do that here even if you still error towards not enforcing higher baseline.

**Comment by bdhave** [comment]
I totally agree with Jeremy.
But to protect from Man in the Middle attacks, version 3.8.1 is the minimum required version with some configuration in the settings.xml.
So 3.6.3 is certainly an valid base.
And 3.8.1 will be in the next 2 years required in EU due to the introduction of the Cyber Resilience Act

**Comment by bdhave** [comment]
see this small report:
[INFO] 
[INFO] Require Maven 3.6.3 to use the following plugin updates:
[INFO]   com.github.spotbugs:spotbugs-maven-plugin ................. 4.8.6.2
[INFO]   maven-compiler-plugin ...................................... 3.13.0
[INFO]   maven-dependency-plugin ..................................... 3.8.0
[INFO]   maven-enforcer-plugin ....................................... 3.5.0
[INFO]   maven-failsafe-plugin ....................................... 3.5.0
[INFO]   maven-gpg-plugin ............................................ 3.2.5
[INFO]   maven-javadoc-plugin ....................................... 3.10.0
[INFO]   maven-release-plugin ........................................ 3.1.1
[INFO]   maven-surefire-plugin ....................................... 3.5.0
[INFO]   org.codehaus.mojo:versions-maven-plugin .................... 2.17.1

So, 3.6.3 seems to be a requirement
